
    <div id="footerwrap">
      <div class="container">
        <h4>Created by the <a href="http://www.w3.org/community/webpayments/">Web Payments Community Group</a>. Shared with love under a <a href="http://creativecommons.org/licenses/by/4.0/">CC-BY</a> license. Thanks to our <a href="<?php echo $TOP_DIR ?>/thanks">contributors</a>.</h4>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    

  <script type="text/javascript" src="<?php echo $TOP_DIR ?>/assets/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="<?php echo $TOP_DIR ?>/assets/js/retina.js"></script>
  <script type="text/javascript" src="<?php echo $TOP_DIR ?>/assets/js/jquery.easing.1.3.js"></script>
  <script type="text/javascript" src="<?php echo $TOP_DIR ?>/assets/js/smoothscroll.js"></script> 
    
  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1539674-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
  })();
  </script>
    
  </body>
</html>

