<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Web Payments">
    <meta name="author" content="Manu Sporny">
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $TOP_DIR ?>/favicon.ico">

    <title>Web Payments</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="<?php echo $TOP_DIR ?>/assets/css/bootstrap.css">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="<?php echo $TOP_DIR ?>/assets/css/main.css">
    <link rel="stylesheet" href="<?php echo $TOP_DIR ?>/assets/css/icomoon.css">
    <link rel="stylesheet" href="<?php echo $TOP_DIR ?>/assets/css/animate-custom.css">

    <link rel='stylesheet' href='//fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' type='text/css'>
    <link rel='stylesheet' href='//fonts.googleapis.com/css?family=Raleway:400,300,700' type='text/css'>

    <script src="<?php echo $TOP_DIR ?>/assets/js/jquery.min.js"></script>
  <script type="text/javascript" src="<?php echo $TOP_DIR ?>/assets/js/modernizr.custom.js"></script>
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="<?php echo $TOP_DIR ?>/assets/js/html5shiv.js"></script>
      <script src="<?php echo $TOP_DIR ?>/assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body data-target="#navbar-nav" data-spy="scroll">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <img class="navbar-logo" src="<?php echo $TOP_DIR ?>/images/logo-32.png">
          </button>
          <a class="navbar-brand hidden-xs hidden-sm" href="#home"><img class="navbar-logo" src="<?php echo $TOP_DIR ?>/images/logo-32.png"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="<?php echo $TOP_DIR ?>/#home" class="smoothScroll">Home</a></li>
            <li> <a href="<?php echo $TOP_DIR ?>/#about" class="smoothScroll"> About</a></li>
            <li> <a href="<?php echo $TOP_DIR ?>/#tech" class="smoothScroll"> Tech</a></li>
            <li> <a href="<?php echo $TOP_DIR ?>/#participate" class="smoothScroll"> Participate</a></li>
            <li> <a href="<?php echo $TOP_DIR ?>/#contact" class="smoothScroll"> Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


