<?php
// Service Website URLs
$WEBSITE = "sites.local";
$DEMO_PATH = "payswarm.com/demos/oauth";
$BASE_URL = "https://$WEBSITE/$DEMO_PATH";
$BUY_URL = "https://$WEBSITE/$DEMO_PATH/buy";
$PREVIEW_URL = "https://$WEBSITE/$DEMO_PATH/previews";
$ARTICLES_URL = "https://$WEBSITE/$DEMO_PATH/articles";

// PaySwarm Authority consumer key and secret
$consumer_key = 'devclient';
$consumer_secret = 'password';

// PaySwarm Authority URLs
$PAYSWARM_AUTHORITY = "localhost:19100";
$AUTHORIZE_URL = "https://$PAYSWARM_AUTHORITY/home/authorize";
$REQUEST_URL = "https://$PAYSWARM_AUTHORITY/api/3.2/oauth1/tokens/request";
$ACCESS_URL = "https://$PAYSWARM_AUTHORITY/api/3.2/oauth1/tokens";
$CONTRACTS_URL = "https://$PAYSWARM_AUTHORITY/api/3.2/oauth1/contracts";
?>

